#!/bin/bash

CONFIG_FILE="config.h"

# Set default configs
DEFAULT_RELEASE=false
DEFAULT_ARCH_TYPE="ARCH_X86"
DEFAULT_LOG_LEVEL=2


# Load default configs if not set
if [[ -z "$RELEASE" ]]; then
    RELEASE=$DEFAULT_RELEASE
fi
if [[ -z "$ARCH_TYPE" ]]; then
    ARCH_TYPE=$DEFAULT_ARCH_TYPE
fi
if [[ -z "$LOG_LEVEL" ]]; then
    LOG_LEVEL=$DEFAULT_LOG_LEVEL
fi

# Function to write to config
writeconfig() {
    echo "$1" >> $CONFIG_FILE
}

# Start with a new file
rm -rf $CONFIG_FILE
touch $CONFIG_FILE

# Add edit warning
autogen_msg="
/**
 * DO NOT EDIT!
 * This file has been auto-generated by configure.sh
 */
"
writeconfig "$autogen_msg"

# Open include guard
writeconfig "#ifndef CONFIG_H_9LYYBTSW"
writeconfig "#define CONFIG_H_9LYYBTSW"
writeconfig

# Set build type options
if [[ "$RELEASE" == true ]]; then
    DEBUG=false
    writeconfig "/* Building in release mode */"
    writeconfig
else
    DEBUG=true
    writeconfig "/* Building in debug mode */"
    writeconfig "#define DEBUG"
    writeconfig "#define DEBUG_TO_SERIAL"
    writeconfig
fi

writeconfig "/* Setting log level to WARN */"
writeconfig "#define LOG_LEVEL $LOG_LEVEL"
writeconfig

writeconfig "/* Building for $ARCH_TYPE architecture */"
writeconfig "#define $ARCH_TYPE"
writeconfig

# Close include guard
writeconfig "#endif /* end of include guard */"
