#!/bin/bash

CONFIG_FILE="config.h"

function writeconfig() {
    echo "$1" >> $CONFIG_FILE
}

# Start with a new file
rm -rf $CONFIG_FILE
touch $CONFIG_FILE

# Add edit warning
autogen_msg="
/**
 * DO NOT EDIT!
 * This file has been auto-generated by configure.sh
 */
"
writeconfig "$autogen_msg"

# Open include guard
writeconfig "#ifndef CONFIG_H_9LYYBTSW"
writeconfig "#define CONFIG_H_9LYYBTSW"
writeconfig

# Set build type options
if [[ -z "$RELEASE" || "$RELEASE" == false ]]; then
    DEBUG=true
    writeconfig "/* Building in debug mode */"
    writeconfig "#define DEBUG"
    writeconfig "#define DEBUG_TO_SERIAL"
    writeconfig
else
    DEBUG=false
    writeconfig "/* Building in release mode */"
    writeconfig
fi

writeconfig "/* Setting log level to WARN */"
writeconfig "#define LOG_LEVEL 2"
writeconfig

writeconfig "/* Building for x86 architecture */"
writeconfig "#define ARCH_X86"
writeconfig

# Close include guard
writeconfig "#endif /* end of include guard */"
